import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAppState } from '@/services/appState.jsx';
import { getStoryBySlug, getNextPassage, getAvailableModels, updateStory, forkStory } from '@/services/mockApi';
import { useDocumentTitle } from '@/utils/seo';
import { isValidSlug } from '@/utils/slugify';
import StoryPassage from '@/components/ui/StoryPassage';
import Dropdown from '@/components/common/Dropdown';

/**
 * StoryReader: Interactive story reading interface with passages and free-text responses
 * 
 * Displays story passages with streaming text and player responses.
 * Maintains scrollable history of previous passages and selections.
 * Fetches next passage when user submits response text.
 * 
 * Features:
 * - Passage history with streaming current passage
 * - Choice-driven narrative progression
 * - Auto-scroll to new passages
 * - Loading and error states
 * - Full-screen immersive layout
 * 
 * Layout:
 * - Full viewport coverage (100vw x 100vh)
 * - Scrollable passage container
 * - Dark gradient background
 * - Smooth animations
 * 
 * @returns {JSX.Element} StoryReader UI
 */
export default function StoryReader() {
  const { state, dispatch } = useAppState();
  const { slug } = useParams();
  const navigate = useNavigate();
  const [story, setStory] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isLoadingChoice, setIsLoadingChoice] = useState(false);
  const [isStreamingPassage, setIsStreamingPassage] = useState(false);
  const [retryResponse, setRetryResponse] = useState(null);
  const [isNearBottom, setIsNearBottom] = useState(true);
  const [canScroll, setCanScroll] = useState(false);
  const [models, setModels] = useState([]);
  const [modelsLoading, setModelsLoading] = useState(true);
  
  const scrollContainerRef = useRef(null);
  const currentPassageRef = useRef(null);
  const shouldAutoScrollRef = useRef(true);
  const hasAutoGeneratedRef = useRef(false);

  // Determine if current user owns this story
  const isOwnStory = story && state.user && story.author_id === state.user.id;

  // Auto-generate next passage when story loads and last passage is user response (indicates fork)
  useEffect(() => {
    if (!story || isOwnStory || isLoadingChoice || isStreamingPassage || hasAutoGeneratedRef.current) {
      return;
    }

    // Check if the last passage is a user response (meaning we just forked)
    const lastPassageIndex = story.passages?.length ? story.passages.length - 1 : -1;
    const lastPassage = lastPassageIndex >= 0 ? story.passages[lastPassageIndex] : null;
    const isLastUserResponse = lastPassageIndex % 2 === 1;

    if (lastPassage && isLastUserResponse && !state.selectedModel) {
      // Wait for model to be selected
      return;
    }

    if (lastPassage && isLastUserResponse && state.selectedModel) {
      hasAutoGeneratedRef.current = true;
      
      console.log('Auto-generating response after fork...');
      
      // Extract the user's response text and generate next passage
      const userResponseText = lastPassage.text || lastPassage.content || '';
      const newPassageId = `passage-${Date.now()}`;
      
      setIsStreamingPassage(true);

      (async () => {
        try {
          const modelId = state.selectedModel.ollamaTag || state.selectedModel.id;

          const context = {
            fandom: story.setup_context?.fandom || story.fandom || 'Original',
            character: story.setup_context?.character || 'The protagonist',
            storyTitle: story.title || 'Untitled Tale',
            passageHistory: story.passages.slice(-2).map(p => p.text || p.content || ''),
            userResponse: userResponseText,
          };

          // Insert placeholder for streaming (assistant is inferred by index)
          setStory(prevStory => ({
            ...prevStory,
            passages: [
              ...prevStory.passages,
              {
                id: newPassageId,
                text: '',
                content: '',
                displayedAt: new Date().toISOString(),
              }
            ],
            currentPassageIndex: prevStory.passages.length,
          }));

          const nextPassage = await getNextPassage(story.id, userResponseText, {
            modelId,
            context,
            onToken: (token) => {
              setStory(prevStory => {
                const updatedPassages = [...prevStory.passages];
                const targetIndex = updatedPassages.findIndex(p => p.id === newPassageId);

                if (targetIndex === -1) {
                  return prevStory;
                }

                updatedPassages[targetIndex] = {
                  ...updatedPassages[targetIndex],
                  text: `${updatedPassages[targetIndex].text || ''}${token}`,
                  content: `${updatedPassages[targetIndex].content || ''}${token}`,
                };

                return {
                  ...prevStory,
                  passages: updatedPassages,
                };
              });
            },
          });

          setStory(prevStory => {
            const updatedPassages = [...prevStory.passages];
            const targetIndex = updatedPassages.findIndex(p => p.id === newPassageId);

            if (targetIndex !== -1) {
              updatedPassages[targetIndex] = {
                ...updatedPassages[targetIndex],
                text: nextPassage.text,
                content: nextPassage.text,
              };
            }

            // Persist to database after generation completes
            (async () => {
              try {
                const cleanedPassages = updatedPassages.map(p => ({
                  text: p.text || '',
                  content: p.content || p.text || '',
                }));
                await updateStory(story.id, { passages: cleanedPassages });
                console.log('Auto-generated passages saved to database');
              } catch (saveError) {
                console.error('Failed to save auto-generated passages:', saveError);
              }
            })();

            return {
              ...prevStory,
              passages: updatedPassages,
            };
          });

          shouldAutoScrollRef.current = true;
        } catch (error) {
          console.error('Failed to auto-generate response:', error);
          setError('Failed to generate your story continuation. Try refreshing.');
        } finally {
          setIsStreamingPassage(false);
        }
      })();
    }
  }, [story, isOwnStory, isLoadingChoice, isStreamingPassage, state.selectedModel]);

  // Update document title with story title
  useDocumentTitle({ storyTitle: story?.title });

  // Redirect if connection check completes and is not online
  useEffect(() => {
    if (state.connectionStatus !== 'CHECKING' && state.connectionStatus !== 'ONLINE') {
      navigate('/', { replace: true });
    }
  }, [state.connectionStatus, navigate]);

  // Load available models for dropdown
  useEffect(() => {
    let isMounted = true;

    async function loadModels() {
      try {
        setModelsLoading(true);
        const availableModels = await getAvailableModels();
        if (!isMounted) return;
        setModels(availableModels);
      } catch (modelError) {
        console.error('Model load failed:', modelError);
        // Fail silently - user can still use existing selected model
      } finally {
        if (isMounted) {
          setModelsLoading(false);
        }
      }
    }

    loadModels();

    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    let isMounted = true;

    /**
     * Loads the current story using slug from URL params.
     * This enables direct URL access and bookmarking.
     * 
     * Validates passage structure: even count = problem (incomplete user response).
     * If detected, removes the incomplete user response and updates DB.
     * 
     * @returns {Promise<void>}
     */
    async function loadStory() {
      try {
        setLoading(true);
        setError(null);

        const normalizedSlug = String(slug || '').trim().toLowerCase();
        if (!normalizedSlug || !isValidSlug(normalizedSlug)) {
          navigate('/', { replace: true });
          return;
        }

        // Fetch story details using slug
        let storyData = await getStoryBySlug(normalizedSlug);
        
        if (!isMounted) return;

        // Ensure story has passages array
        if (!storyData.passages || storyData.passages.length === 0) {
          throw new Error('Story has no passages');
        }

        // Validate passage structure: if even count, last passage is incomplete user response
        // Should have odd count: 1 bot (index 0), then alternating user-bot
        if (storyData.passages.length % 2 === 0) {
          console.log(`Story has even passage count (${storyData.passages.length}). Removing incomplete user response...`);
          
          try {
            // Remove last passage locally
            const updatedPassages = storyData.passages.slice(0, -1);
            storyData = { ...storyData, passages: updatedPassages };
            
            // Update the story in the database for owned stories
            if (state.user && storyData.author_id === state.user.id) {
              try {
                const response = await fetch(
                  `/api/stories/${storyData.id || storyData.slug}`,
                  {
                    method: 'PUT',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ passages: updatedPassages }),
                    credentials: 'include',
                  }
                );
                
                if (response.ok) {
                  console.log('Incomplete user response removed from database');
                } else {
                  console.warn('Failed to clean passages in database, but local copy updated');
                }
              } catch (dbUpdateError) {
                console.warn('Could not update database, but local copy is clean:', dbUpdateError);
              }
            } else {
              console.log('Incomplete user response removed from local copy (read-only story)');
            }
          } catch (updateError) {
            console.error('Error cleaning incomplete response:', updateError);
          }
        }

        setStory(storyData);
      } catch (err) {
        console.error('Failed to load story:', err);
        if (!isMounted) return;
        setError('The tale eludes our grasp. Return to the archives.');
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    }

    loadStory();

    return () => {
      isMounted = false;
    };
  }, [slug, navigate]);

  /**
   * Auto-scroll to current passage when new passage is added
   */
  useEffect(() => {
    const scrollContainer = scrollContainerRef.current;
    if (!scrollContainer) {
      return undefined;
    }

    /**
     * Tracks whether the reader is near the bottom of the passage list.
     * Used to decide whether to auto-scroll or show "go to latest" button.
     */
    const handleScroll = () => {
      const distanceFromBottom =
        scrollContainer.scrollHeight - scrollContainer.scrollTop - scrollContainer.clientHeight;
      setIsNearBottom(distanceFromBottom <= 160);
      setCanScroll(scrollContainer.scrollHeight > scrollContainer.clientHeight + 8);
    };

    handleScroll();
    scrollContainer.addEventListener('scroll', handleScroll, { passive: true });

    return () => {
      scrollContainer.removeEventListener('scroll', handleScroll);
    };
  }, []);

  useEffect(() => {
    const scrollContainer = scrollContainerRef.current;
    if (!story || !scrollContainer) {
      return undefined;
    }

    setCanScroll(scrollContainer.scrollHeight > scrollContainer.clientHeight + 8);

    // Only auto-scroll if user is near bottom OR they just submitted a response
    if (!isNearBottom && !shouldAutoScrollRef.current) {
      return undefined;
    }

    const timer = setTimeout(() => {
      scrollContainer.scrollTo({
        top: scrollContainer.scrollHeight,
        behavior: 'smooth',
      });
      setIsNearBottom(true);
      shouldAutoScrollRef.current = false; // Reset after scrolling
    }, 120);

    return () => clearTimeout(timer);
  }, [story?.passages?.length]); // Only trigger when passages change, not when scroll position changes

  /**
   * Scrolls the reading container to the latest passage.
   */
  const handleScrollToLatest = () => {
    const scrollContainer = scrollContainerRef.current;
    if (!scrollContainer) {
      return;
    }

    scrollContainer.scrollTo({
      top: scrollContainer.scrollHeight,
      behavior: 'smooth',
    });
  };

  /**
   * Handle response submission - add user response, generate next passage, save to DB
   * 
   * @param {string} responseText - User free-text response
   */
  const handleResponseSubmit = async (responseText) => {
    if (!story || isLoadingChoice) return;

    const trimmedResponse = String(responseText || '').trim();
    if (!trimmedResponse) return;

    // Check if model is selected before allowing response submission
    if (!state.selectedModel) {
      setError('Please select an AI model from the dashboard before continuing the story.');
      return;
    }

    if (!isOwnStory) {
      setError('Fork this story first to continue writing.');
      return;
    }

    let userPassageId = null;
    let aiPassageId = null;

    setIsLoadingChoice(true);
    setError(null);
    setRetryResponse({ responseText: trimmedResponse });
    shouldAutoScrollRef.current = true; // Always scroll to new passage after response

    try {
      const modelId = state.selectedModel.ollamaTag || state.selectedModel.id;
      userPassageId = `passage-${Date.now()}-user`;
      aiPassageId = `passage-${Date.now()}-ai`;
      const recentPassageText = story.passages[story.passages.length - 1]?.text || '';

      const context = {
        fandom: story.setup_context?.fandom || story.fandom || 'Original',
        character: story.setup_context?.character || 'The protagonist',
        storyTitle: story.title || 'Untitled Tale',
        passageHistory: recentPassageText ? [recentPassageText] : [],
        userResponse: trimmedResponse,
      };

      // 1. Add user response passage (user/assistant inferred by index)
      setStory(prevStory => {
        const updatedPassages = [...prevStory.passages];
        
        // Add user response passage
        updatedPassages.push({
          id: userPassageId,
          text: trimmedResponse,
          content: trimmedResponse,
          displayedAt: new Date().toISOString(),
        });
        
        // Add placeholder for AI response
        updatedPassages.push({
          id: aiPassageId,
          text: '',
          content: '',
          displayedAt: new Date().toISOString(),
        });

        return {
          ...prevStory,
          passages: updatedPassages,
          currentPassageIndex: prevStory.passages.length,
          lastModified: new Date().toISOString(),
        };
      });

      setIsStreamingPassage(true);

      // 2. Generate AI response
      const nextPassage = await getNextPassage(story.id, trimmedResponse, {
        modelId,
        context,
        onToken: (token) => {
          // Stream tokens into AI passage
          setStory(prevStory => {
            const updatedPassages = [...prevStory.passages];
            const targetIndex = updatedPassages.findIndex(p => p.id === aiPassageId);

            if (targetIndex === -1) {
              return prevStory;
            }

            const currentText = updatedPassages[targetIndex].text || '';
            updatedPassages[targetIndex] = {
              ...updatedPassages[targetIndex],
              text: currentText + token,
              content: currentText + token,
            };

            return {
              ...prevStory,
              passages: updatedPassages,
            };
          });
        },
      });

      // 3. Update AI passage with complete generated text
      setStory(prevStory => {
        const updatedPassages = [...prevStory.passages];
        const targetIndex = updatedPassages.findIndex(p => p.id === aiPassageId);

        if (targetIndex !== -1) {
          updatedPassages[targetIndex] = {
            ...updatedPassages[targetIndex],
            text: nextPassage.text,
            content: nextPassage.text,
          };
        }

        // Clean up temporary IDs and prepare for DB save
        const cleanedPassages = updatedPassages.map(p => ({
          text: p.text || '',
          content: p.content || p.text || '',
        }));

        // 4. Persist both user response and AI response to database
        (async () => {
          try {
            await updateStory(story.id, { passages: cleanedPassages });
            console.log('Story passages saved to database');
          } catch (saveError) {
            console.error('Failed to save passages to database:', saveError);
            // Don't show error to user - local state is already updated
          }
        })();

        const totalWords = updatedPassages.reduce((sum, p) => {
          return sum + ((p.text || '').split(/\s+/).length || 0);
        }, 0);

        return {
          ...prevStory,
          passages: updatedPassages,
          wordCount: totalWords,
        };
      });

      setRetryResponse(null);
    } catch (err) {
      console.error('Failed to get next passage:', err);
      setError(err.message || 'The threads of fate are tangled. Try again?');
      
      // Remove both user and AI passages on error
      setStory(prevStory => {
        const updatedPassages = prevStory.passages.filter(
          p => p.id !== userPassageId && p.id !== aiPassageId
        );
        return {
          ...prevStory,
          passages: updatedPassages,
          currentPassageIndex: Math.max(0, prevStory.passages.length - 1),
        };
      });
    } finally {
      setIsLoadingChoice(false);
      setIsStreamingPassage(false);
    }
  };

  /**
   * Retry failed response submission
   */
  const handleRetry = () => {
    if (retryResponse) {
      handleResponseSubmit(retryResponse.responseText);
    }
  };

  /**
   * Fork the current non-owned story and open the forked slug.
   */
  const handleForkStory = async () => {
    if (!story || isLoadingChoice) {
      return;
    }

    if (!state.user) {
      setError('Please sign in to fork this story.');
      return;
    }

    setIsLoadingChoice(true);
    setError(null);

    try {
      const fork = await forkStory(story.id || story.slug);
      if (fork?.slug) {
        navigate(`/story/${fork.slug}`, { replace: true });
        return;
      }

      throw new Error('Fork created but no slug was returned.');
    } catch (forkError) {
      console.error('Failed to fork story:', forkError);
      setError(forkError.message || 'Failed to fork story. Please try again.');
    } finally {
      setIsLoadingChoice(false);
    }
  };

  // Loading state: keep StoryReader invisible until content is ready
  if (loading) {
    return null;
  }

  // Error state (initial load)
  if (error && !story) {
    return (
      <div className="fixed inset-0 z-20 bg-gradient-to-b from-gray-900 via-blue-950 to-black flex items-center justify-center animate-[fadeIn_0.8s_ease-in]">
        <div className="text-center max-w-md px-6">
          <p className="text-red-400 text-xl mb-4">{error}</p>
          <p className="text-blue-200">Close this window and try again.</p>
        </div>
      </div>
    );
  }

  const currentPassageIndex = story?.currentPassageIndex ?? 0;

  /**
   * Navigate back to dashboard with reverse animation
   */
  const handleBackToDashboard = () => {
    dispatch({ type: 'TRANSITION_TO_DASHBOARD' });
    navigate('/dashboard');
  };

  /**
   * Handles AI model selection change.
   *
   * @param {string} modelId - Selected model ID
   * @returns {void}
   */
  const handleModelChange = (modelId) => {
    const selectedModel = models.find(m => m.id === modelId);
    if (selectedModel) {
      // Persist to localStorage for page reloads
      try {
        localStorage.setItem('selectedModel', JSON.stringify(selectedModel));
      } catch (storageError) {
        console.warn('Failed to persist selected model:', storageError);
      }

      dispatch({
        type: 'MODEL_SELECTED',
        payload: { model: { ...selectedModel, ollamaTag: selectedModel.id } }
      });
    }
  };

  // Prepare model options for dropdown
  const modelOptions = models.map(model => ({
    value: model.id,
    label: model.displayName
  }));

  // Story display with passages
  // Fade in only after animation completes
  const isAnimationComplete = !state.isTransitioning;
  return (
    <div 
      ref={scrollContainerRef}
      className={`story-scrollbar fixed inset-0 z-20 bg-gradient-to-b from-gray-900 via-blue-950 to-black overflow-y-auto transition-opacity duration-500 ${
        isAnimationComplete ? 'animate-[fadeIn_1.2s_ease-in]' : 'opacity-0 pointer-events-none'
      }`}
    >
      {/* Back to Dashboard Button */}
      <button
        type="button"
        onClick={handleBackToDashboard}
        disabled={state.isTransitioning}
        className="fixed top-6 left-6 z-50 px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 text-white rounded-lg transition-colors font-medium"
        title="Return to Dashboard"
      >
        ← Dashboard
      </button>

      <div className="min-h-screen flex items-start justify-center px-6 py-12">
        <article className="w-[80vw] max-w-[80vw] mx-auto">
          
          {/* Story header */}
          <header className="mb-12 text-center animate-[fadeUp_1.4s_ease-out] sticky top-0 bg-gradient-to-b from-gray-900 via-blue-950/90 to-transparent py-6 z-10 backdrop-blur-sm">
            <h1 className="text-4xl md:text-5xl font-bold text-gray-100 mb-3">
              {story.title}
            </h1>
            <p className="text-blue-300 text-lg">
              {story.fandom}
            </p>
            <div className="text-blue-200 text-sm mt-2 opacity-70">
              {story.wordCount} words
            </div>
          </header>

          {/* Passage history */}
          <div className="space-y-12 animate-[fadeUp_1.6s_ease-out]">
            {story.passages.map((passage, index) => (
              <div 
                key={passage.id}
                ref={index === currentPassageIndex ? currentPassageRef : null}
              >
                <StoryPassage
                  passage={passage}
                  passageIndex={index}
                  isCurrent={index === currentPassageIndex}
                  isLoadingChoice={isLoadingChoice}
                />
              </div>
            ))}
          </div>

          {/* Response input form at bottom (owners only) */}
          {story && story.passages && story.passages.length > 0 && isOwnStory && (
            <div className="mt-12 p-6 border-2 border-blue-600/40 bg-blue-950/20 rounded-lg">
              <p className="text-blue-300 text-sm mb-4 italic font-semibold">
                What will you do next?
              </p>
              <div className="space-y-3">
                <textarea
                  value={retryResponse?.responseText || ''}
                  onChange={(event) => setRetryResponse({ responseText: event.target.value })}
                  onKeyDown={(event) => {
                    if ((event.ctrlKey || event.metaKey) && event.key === 'Enter' && !isLoadingChoice) {
                      handleResponseSubmit(event.target.value);
                    }
                  }}
                  disabled={isLoadingChoice || isStreamingPassage}
                  placeholder="Write your action or decision..."
                  rows={4}
                  className="w-full rounded-lg border border-blue-600/40 bg-blue-950/30 text-gray-100 px-4 py-3 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-60"
                />
                <button
                  type="button"
                  onClick={() => {
                    const text = retryResponse?.responseText || '';
                    if (text.trim()) {
                      handleResponseSubmit(text);
                    }
                  }}
                  disabled={isLoadingChoice || isStreamingPassage || (retryResponse?.responseText || '').trim().length === 0}
                  className="w-full rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 py-3 text-white font-semibold transition-all hover:from-blue-700 hover:to-blue-800 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isLoadingChoice ? 'Processing...' : 'Continue Story'}
                </button>
                <p className="text-xs text-blue-300/80">
                  Tip: Press Ctrl+Enter to submit quickly.
                </p>
              </div>
            </div>
          )}

          {/* Fork action for non-owned stories */}
          {story && story.passages && story.passages.length > 0 && !isOwnStory && (
            <div className="mt-12 p-6 border-2 border-blue-600/40 bg-blue-950/20 rounded-lg">
              <p className="text-blue-300 text-sm mb-4 italic font-semibold">
                This tale belongs to another author.
              </p>
              <button
                type="button"
                onClick={handleForkStory}
                disabled={isLoadingChoice || isStreamingPassage}
                className="w-full rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 py-3 text-white font-semibold transition-all hover:from-blue-700 hover:to-blue-800 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isLoadingChoice ? 'Forking...' : 'Fork Story To Continue'}
              </button>
            </div>
          )}

          {/* Error message (during choice selection) */}
          {error && story && (
            <div className="mt-8 p-6 bg-red-900/30 border-l-4 border-red-500 rounded-r-lg animate-[fadeIn_0.4s_ease-in]">
              <p className="text-red-300 text-lg mb-4">{error}</p>
              <button
                onClick={handleRetry}
                className="px-6 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg transition-colors"
              >
                Retry
              </button>
            </div>
          )}

        </article>
      </div>

      {/* Model Selector - Bottom Right */}
      {!modelsLoading && models.length > 0 && isAnimationComplete && (
        <div className="fixed bottom-6 right-6 z-40 animate-[fadeUp_0.6s_ease-out]">
          <label className="block text-xs font-semibold text-blue-300 mb-2">
            AI Energy Source
          </label>
          <div className="w-48">
            <Dropdown
              options={modelOptions}
              value={state.selectedModel?.ollamaTag || state.selectedModel?.id || ''}
              onChange={handleModelChange}
              placeholder="Select model..."
              className="text-sm"
            />
          </div>
          {state.selectedModel && (
            <p className="text-xs text-blue-200 mt-1">
              {state.selectedModel.displayName || state.selectedModel.name}
            </p>
          )}
        </div>
      )}

      {/* Go to latest passage button - Fixed positioning outside article */}
      {canScroll && !isNearBottom && isAnimationComplete && (
        <div className="fixed bottom-6 right-64 z-50">
          <button
            type="button"
            onClick={handleScrollToLatest}
            className="rounded-full bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 shadow-2xl transition-all hover:scale-105 font-medium"
          >
            ↓ Latest Passage
          </button>
        </div>
      )}
    </div>
  );
}
